version: '3.5'
services:

  app:
    container_name: epic-tnt-bridge
    build:
      context: .
      dockerfile: Dockerfile
    image: epic-tnt-bridge:latest
    restart: always
    ports:
        - 5500:5000
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
      - ./logs:/app/logs
    networks:
      - backnet

networks:
  backnet:
    name: etb_backnet
