openapi: 3.0.3
info:
  title: EPIC FHIR Schema Mapping To TNT Schema
  description: |
    API for managing hospital encounters and patient information, mapped from EPIC FHIR to adhere with TNT Schema.
    The `patient/encounter` endpoint takes a patient ID as a parameter and retrieves only encounters 
    that involve hospitalization.

    ### Conditions for different types of locations, hospital, department, room, or bed
    Visit ```fhir_location.FhirLocation``` class  for details and ```rawdata```  refers to the raw data from EPIC.
      - **Hospital location**:
      A location in an encounter is considered a hospital if it includes an "inpatient" type in its coding or if it has a "TAX" code in its identifiers.
      ```python
      def is_hospital(self):
          # @TODO Look for "inpatient" in type > coding still to be confirmed
          taxed = [code for code in self.get_object_detail(self.rawdata, ["type", "coding"], []) if code['code'] == "TAX"]
          return len(taxed) > 0
      ```
    - **Department**:
      A location in an encounter is considered a department if it has both `managingOrganization` and `partOf` fields.
      ```python
      def is_department(self):
          return "managingOrganization" in self.rawdata and "partOf" in self.rawdata
      ```
    - **Room**:
      A location in an encounter is considered a room if it follows the HL7 standard of having a room code.
      ```python
      def is_room(self):
          _is_room = self.get_object_detail(self.rawdata, ["encounter_data", "physicalType", "coding", 0, "code"]) == "ro"
          if _is_room:
              loc_ref = self.get_object_detail(self.rawdata, ["encounter_data", "location", "reference"])
              loc_id = loc_ref.split("/")[1]
              return FhirLocation.fetch_by_id(loc_id)
      ```
    - **Bed**:
      A location in  encounter is considered a bed if it follows the HL7 standard of having a bed code.
      ```python
      def is_bed(self):
          _is_bed = self.get_object_detail(self.rawdata, ["encounter_data", "physicalType", "coding", 0, "code"]) == "bd"
          if (_is_bed) {
              return {
                  "id": self.get_object_detail(self.rawdata, ["encounter_data", "identifier", "value"])
              }
      ```

    ### Mapping from EPIC FHIR to TNT Schema

    - **hospital.id**: Mapped from `Encounter.location[].location.reference`
    - **patient.id**: Mapped from `Encounter.subject.reference`
    - **patient.version**: Mapped from `Encounter.subject.version`
    - **patient.first_name**: Mapped from `Patient.name[].given[0]`
    - **patient.last_name**: Mapped from `Patient.name[].family`
    - **patient.date_of_birth**: Mapped from `Patient.birthDate`
    - **patient.gender**: Mapped from `Patient.gender`
    - **patient.is_deleted**: Mapped from `Patient.active` (negated)
    - **patient.alternative_ids**: Mapped from `Patient.identifier[].value` (excluding identifiers with system `http://open.epic.com/FHIR/StructureDefinition/identifier`)
    - **hospital_stay.id**: Mapped from `Encounter.id`
    - **hospital_stay.version**: Generate date-time (not directly from EPIC)
    - **hospital_stay.patient.id**: Mapped from `Encounter.subject.reference`
    - **hospital_stay.from_at**: Mapped from `Encounter.period.start`
    - **hospital_stay.until_at**: Mapped from `Encounter.period.end`
    - **hospital_stay.is_pre_discharge**: Mapped from `Encounter.class.display` with value `Discharge`
    - **hospital_stay.is_pre_admission**: Mapped from `Encounter.class.display` with value `Preadmission`
    - **hospital_stay.reason_of_discharge**: Mapped from `Encounter.hospitalization.dischargeDisposition.text`
    - **hospital_stay.hospital.id**: Mapped from `Encounter.location[].location.reference`
    - **department_stays.id**: Mapped from `Encounter.location[].id`
    - **department_stays.hospital_stay.id**: Mapped from `Encounter.id`
    - **department_stays.version**: Generate date-time (not directly from EPIC)
    - **department_stays.location.hospital.id**: Mapped from `Encounter.location[].location.reference`
    - **department_stays.location.venue.id**: Mapped from `Encounter.location[].location.reference`
    - **department_stays.location.department.id**: Mapped from `Encounter.location[].location.reference`
    - **department_stays.location.room.id**: Mapped from `Encounter.location[3].location.reference`
    - **department_stays.location.bed.id**: Mapped from `Encounter.location[4].identifier.value`
    - **department_stays.starts_at**: Mapped from `Encounter.location[].period.start`
  version: 1.0.0
paths:
  /patient/encounter:
    get:
      summary: Retrieve patient encounters
      parameters:
        - name: patientId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier for the patient
      responses:
        '200':
          description: A list of patient encounters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EncounterResponse'
components:
  schemas:
    EncounterResponse:
      type: object
      properties:
        hospital:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the hospital
        patient:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the patient
            version:
              type: string
              nullable: true
              description: Version of the patient record
            first_name:
              type: string
              description: Patient's first name
            last_name:
              type: string
              description: Patient's last name
            date_of_birth:
              type: string
              format: date
              description: Patient's date of birth
            gender:
              type: string
              description: Patient's gender
            is_deleted:
              type: boolean
              description: Whether the patient record is deleted
            alternative_ids:
              type: array
              items:
                type: string
              description: List of alternative identifiers for the patient
        hospital_stay:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the hospital stay
            version:
              type: string
              nullable: true
              description: Version of the hospital stay record
            patient:
              type: object
              properties:
                id:
                  type: string
                  description: Unique identifier for the patient
                version:
                  type: string
                  nullable: true
                  description: Version of the patient record
                first_name:
                  type: string
                  description: Patient's first name
                last_name:
                  type: string
                  description: Patient's last name
                date_of_birth:
                  type: string
                  format: date
                  description: Patient's date of birth
                gender:
                  type: string
                  description: Patient's gender
                is_deleted:
                  type: boolean
                  description: Whether the patient record is deleted
                alternative_ids:
                  type: array
                  items:
                    type: string
                  description: List of alternative identifiers for the patient
            from_at:
              type: string
              format: date-time
              description: Start date and time of the hospital stay
            until_at:
              type: string
              format: date-time
              nullable: true
              description: End date and time of the hospital stay
            is_pre_discharge:
              type: boolean
              description: Whether the patient is pre-discharge
            is_pre_admission:
              type: boolean
              description: Whether the patient is pre-admission
            reason_of_discharge:
              type: string
              nullable: true
              description: Reason for discharge
            hospital:
              type: object
              properties:
                id:
                  type: string
                  description: Unique identifier for the hospital
        department_stays:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Unique identifier for the department stay
              hospital_stay:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier for the hospital stay
              version:
                type: string
                nullable: true
                description: Version of the department stay record
              location:
                type: object
                properties:
                  hospital:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique identifier for the hospital
                  venue:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique identifier for the venue
                  department:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique identifier for the department
                  room:
                    type: object
                    properties:
                      id:
                        type: string
                        nullable: true
                        description: Room identifier
                  bed:
                    type: object
                    properties:
                      id:
                        type: string
                        nullable: true
                        description: Bed identifier
              starts_at:
                type: string
                format: date-time
                nullable: true
                description: Start date and time of the department stay
  examples:
    example1:
      summary: Example Encounter Response 1
      value:
        hospital:
          id: "el.Nc4rfzXa7Ml9v6gin1Pw3"
        patient:
          id: "e0w0LEDCYtfckT6N.CkJKCw3"
          version: null
          first_name: "Warren"
          last_name: "McGinnis"
          date_of_birth: "1952-05-24"
          gender: "male"
          is_deleted: false
          alternative_ids:
            - "E4004"
            - "Z6126"
            - "e0w0LEDCYtfckT6N.CkJKCw3"
            - "Z6126"
            - "203710"
        hospital_stay:
          id: "eucYt0hPWgEMZqybf6t4c.g3"
          version: null
          patient:
            id: "e0w0LEDCYtfckT6N.CkJKCw3"
            version: null
            first_name: "Warren"
            last_name: "McGinnis"
            date_of_birth: "1952-05-24"
            gender: "male"
            is_deleted: false
            alternative_ids:
              - "E4004"
              - "Z6126"
              - "e0w0LEDCYtfckT6N.CkJKCw3"
              - "Z6126"
              - "203710"
          from_at: "2019-05-28T15:22:00Z"
          until_at: null
          is_pre_discharge: false
          is_pre_admission: true
          reason_of_discharge: null
          hospital:
            id: "el.Nc4rfzXa7Ml9v6gin1Pw3"
        department_stays:
          - id: "eucYt0hPWgEMZqybf6t4c.g3-eO-3e71xq6A5Xp7leBMrw5X-8sAl6UHIF91p7maQKFdU3"
            hospital_stay:
              id: "eucYt0hPWgEMZqybf6t4c.g3"
            version: null
            location:
              hospital:
                id: "el.Nc4rfzXa7Ml9v6gin1Pw3"
              venue:
                id: "el.Nc4rfzXa7Ml9v6gin1Pw3"
              department:
                id: "eO-3e71xq6A5Xp7leBMrw5X-8sAl6UHIF91p7maQKFdU3"
              room:
                id: "eBfbAqRm4snhZr6kGdCrH-Q3"
              bed: null
            starts_at: null
    example2:
      summary: Example Encounter Response 2
      value:
        hospital:
          id: "eJMrCj-ZhPORf9uxBLaR4kw3"
        patient:
          id: "erXuFYUfucBZaryVksYEcMg3"
          version: null
          first_name: "Camila"
          last_name: "Lopez"
          date_of_birth: "1987-09-12"
          gender: "female"
          is_deleted: false
          alternative_ids:
            - "E4007"
            - "Z6129"
            - "erXuFYUfucBZaryVksYEcMg3"
            - "Z6129"
            - "203713"
            - "FHIRCAMILA"
            - "736"
        hospital_stay:
          id: "ej567ARSFdaF4ooZVunIlIg3"
          version: null
          patient:
            id: "erXuFYUfucBZaryVksYEcMg3"
            version: null
            first_name: "Camila"
            last_name: "Lopez"
            date_of_birth: "1987-09-12"
            gender: "female"
            is_deleted: false
            alternative_ids:
              - "E4007"
              - "Z6129"
              - "erXuFYUfucBZaryVksYEcMg3"
              - "Z6129"
              - "203713"
              - "FHIRCAMILA"
              - "736"
          from_at: "2023-06-02T20:49:58Z"
          until_at: null
          is_pre_discharge: false
          is_pre_admission: false
          reason_of_discharge: null
          hospital:
            id: "eJMrCj-ZhPORf9uxBLaR4kw3"
        department_stays:
          - id: "ej567ARSFdaF4ooZVunIlIg3-exzJSfs-2YYqMPilpdzkcdMVzw6TB9WJfeqFRVe.cpSo3"
            hospital_stay:
              id: "ej567ARSFdaF4ooZVunIlIg3"
            version: null
            location:
              hospital:
                id: "eJMrCj-ZhPORf9uxBLaR4kw3"
              venue:
                id: "eJMrCj-ZhPORf9uxBLaR4kw3"
              department:
                id: "exzJSfs-2YYqMPilpdzkcdMVzw6TB9WJfeqFRVe.cpSo3"
              room: null
              bed: null
            starts_at: null
