name: Build and Push Docker Image to Repo

permissions:
  packages: write  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Read the Docker image tag from a file
      - name: Read Docker tag from file
        id: read_tag
        run: echo "IMAGE_TAG=$(cat VERSION)" >> $GITHUB_ENV

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.IMAGE_TAG }}

      # Log out from GitHub Container Registry
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
